### ISSUE TITLE
Show more button stays under the text

### ISSUE THREAD

**Issue by Bayramito** [fawaz-ahmed/react-native-read-more#10] opened 2020-10-02 13:15 UTC
Is there any prop or setting to set position for the show more / less buttons? 

Becouse show more buttons stays under the actual text

[https://ibb.co/6m66h5R](https://ibb.co/6m66h5R)

**Comment by fawaz-ahmed** [comment] 2020-10-06 05:25
> Is there any prop or setting to set position for the show more / less buttons?
> 
> Becouse show more buttons stays under the actual text
> 
> https://ibb.co/6m66h5R

@Bayramito can you share screenshot and your code implementation ? So that I may understand better.

**Comment by fawaz-ahmed** [comment] 2020-11-15 18:05
Closing issue for staying idle

**Comment by ghost** [comment] 2021-03-30 08:00
Facing same issue

**Comment by fawaz-ahmed** [comment] 2021-03-30 08:39
Can you please provide a screenshot ? Or some sample text with styles ? So that I can reproduce and fix the issue. Thanks,
________________________________

**Comment by kalmahik** [comment] 2021-06-10 05:15
hi!
the same issue when textAlign: 'right'

**Comment by fawaz-ahmed** [comment] 2021-06-10 18:30
@kalmahik thanks for bringing this up. I can fix this but I'll need some help. Can you share some more details around this so that I can reproduce?
Things like styling, text you're passing, props you're passing and also a screenshot will help.

**Comment by kalmahik** [comment] 2021-06-11 10:28
thank you for your quick reply)

This is OK
<img width="431" alt="Screenshot 2021-06-11 at 13 19 33" src="https://user-images.githubusercontent.com/20880061/121671879-c651af00-cab7-11eb-97e1-eda3e9179cd7.png">

And then I change align to right:
<img width="423" alt="Screenshot 2021-06-11 at 13 20 00" src="https://user-images.githubusercontent.com/20880061/121672039-fdc05b80-cab7-11eb-8be9-3c7333b1aa13.png">

First case (OK): -> {"color": "#1E1E30", "fontSize": 16, "textAlign": "left"}
Second case (NOT OK) -> {"color": "#1E1E30", "fontSize": 16, "textAlign": "right"}

**Comment by ajablanco** [comment] 2021-08-16 18:59
Hi, facing the same issue. Is there a quick fix for this?

**Comment by fawaz-ahmed** [comment] 2021-08-16 21:34
Text align right is not supported. For a quick fix downgrade to version `1.1.5` and supply `backgroundColor` prop

**Comment by fawaz-ahmed** [comment] 2021-12-20 23:09
Closing this issue in favor of
https://github.com/fawaz-ahmed/react-native-read-more/issues/38
Since right align is currently not supported.

**Closed as completed by fawaz-ahmed** 2021-12-20 23:09 UTC
